### ISSUE TITLE
Support cloudpathlib

### ISSUE THREAD

**Issue by ejm714** [drivendataorg/pandas-path#1]
Make pandas_path place nicely with cloudpathlib so we can do things like

```
bucket = S3Path("s3://drivendata-competition-sfp-public/")
df['s3_path'] = bucket / df.filename.path.with_suffix('.tif')
```

**Comment by pjbull** [comment]
Thoughts on the API?

We could add a `.cloud_path` (or `.cloud` or `.cpath` or something else) accessor to explicitly do `CloudPath` things.

Or, we can overload the `.path` accessor to just handle CloudPaths. We'd do this by trying to instantiate everything as `CloudPath` first (and if that fails, because the protocol fails—i.e., it doesn't start with `s3://`, `az://`, etc.) instantiate it as a`Path` object.

In order not to muck with the underlying data types, we convert to `Path` when the accessor is hit (this is where we'd need some changes):
https://github.com/drivendataorg/pandas-path/blob/8b7d1478966084733df09864b680b1eec01da0d8/pandas_path/accessor.py#L35

We also check `isinstance` `Path` in places, and should use `os.PathLike` instead, which both objects will support.

And then we return everything as a `str` so you can continue to do normal `pandas` things with a string type. This should be ok, but worth thinking about:
https://github.com/drivendataorg/pandas-path/blob/8b7d1478966084733df09864b680b1eec01da0d8/pandas_path/accessor.py#L68
https://github.com/drivendataorg/pandas-path/blob/8b7d1478966084733df09864b680b1eec01da0d8/pandas_path/accessor.py#L95

**Comment by jayqi** [comment]
Dependency-wise, it might be easier to think about if it went the other way: cloudpathlib has an (optional?) implementation of pandas-path.

**Comment by pjbull** [comment]
Ah, something like `from cloudpathlib.pandas import cloud_path` to register the accessor?
